### ISSUE TITLE
ua_string: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by shoeffner** [shoeffner/web-openccg#2]
For some requests, the user-agent string seems to be `None`:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./ccgapp.py", line 73, in index
    if is_non_gui_agent(ua):
  File "./ccgapp.py", line 22, in is_non_gui_agent
    ua_string = ua_string.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

Proposed solution:
- No autodetection of user agents anymore, instead rely on users to use the /gui endpoint.
- Alternatively, make an /api endpoint for requests, and / point to the gui.

**Comment by shoeffner** [comment]
Resolved in  0855027.
