### ISSUE TITLE
TatSu failes to parse "put the book and the cup on the table"

### ISSUE THREAD

**Issue by shoeffner** [shoeffner/web-openccg#30]
The server output is as follows:
```
[2018-11-09 19:17:54,321] ERROR in app: Exception on /openccg/parse [POST],
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 203, in parse,
    result = rule(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 84, in _start_,
    self._semspec_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 91, in _semspec_,
    self._term_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 111, in _term_,
    self._gather(block1, sep1),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 797, in _gather,
    return self._closure(block, sep=sep, omitsep=True),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 767, in _closure,
    block(),
  File "./generated_openccg_parser.py", line 110, in block1,
    self._nominal_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 219, in _nominal_,
    self._gather(block5, sep5),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 797, in _gather,
    return self._closure(block, sep=sep, omitsep=True),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 769, in _closure,
    self._repeat(block, prefix=sep, dropprefix=omitsep),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 756, in _repeat,
    self._isolate(block),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 735, in _isolate,
    block(),
  File "./generated_openccg_parser.py", line 218, in block5,
    self._role_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 235, in _role_,
    self._variable_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 186, in _variable_,
    self._gather(block11, sep11),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 797, in _gather,
    return self._closure(block, sep=sep, omitsep=True),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 769, in _closure,
    self._repeat(block, prefix=sep, dropprefix=omitsep),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 759, in _repeat,
    self._error('empty closure'),
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__,
    self.gen.throw(type, value, traceback),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 678, in _option,
    raise FailedCut(e),
tatsu.exceptions.FailedCut: (1:183) no available options :,
(@x2:gs-AffectingDirectedMotion( <mood>imperative ^ <gs-route>(x3:gs-GeneralizedRoute ^ <gs-destination>x4:gs-GeneralizedLocation) ^ <gum-actee>(x1:gum-SimpleThing ^ <relation>and ^ <item1>(w2:slm-Book ^ book ^ <det>the ^ <ident>specific ^ <quant>singular) ^ <item2>w5:slm-Cup) ^ <gum-processInConfiguration>(w0:slm-Putting ^ slm-Driving)) ^ @x6:gs-SpatialLocating( <gs-locatum>(w5:slm-Cup ^ cup ^ <det>the ^ <ident>specific ^ <quant>singular) ^ <gs-placement>(x5:gs-GeneralizedLocation ^ <gs-hasSpatialModality>(w6:gum-FunctionalControlledExternal ^ slm-On) ^ <gs-relatum>(w8:slm-Table ^ slm-Table ^ <det>the ^ <ident>specific ^ <quant>singular)))),
                                                                                                                                                                                      ^,
role,
variable,
role,
nominal,
term,
semspec,
start,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app,
    response = self.full_dispatch_request(),
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request,
    rv = self.handle_user_exception(e),
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception,
    reraise(exc_type, exc_value, tb),
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise,
    raise value,
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "./webopenccg.py", line 71, in parse,
    response = create_response(sentence),
  File "./webopenccg.py", line 30, in create_response,
    content = wccg.parse(sentence),
  File "./wccg.py", line 37, in parse,
    wccg_response = jsonify_parses(wccg_response),
  File "./wccg.py", line 119, in jsonify_parses,
    json_parses[key] = ccg_to_json(parse),
  File "./wccg.py", line 135, in ccg_to_json,
    parseinfo=False)),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 208, in parse,
    raise self._furthest_exception,
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 672, in _option,,
d,
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 756, in _repeat,
    self._isolate(block),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 735, in _isolate,
    block(),
  File "./generated_openccg_parser.py", line 185, in block11,
    self._role_(),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 54, in wrapper,
    return self._call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 509, in _call,
    result = self._recursive_call(ruleinfo),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 540, in _recursive_call,
    result = self._invoke_rule(ruleinfo, key),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 573, in _invoke_rule,
    ruleinfo.impl(self),
  File "./generated_openccg_parser.py", line 249, in _role_,
    self._error('no available options'),
  File "/usr/local/lib/python3.6/dist-packages/tatsu/contexts.py", line 435, in _error,
    raise self._make_exception(item, exclass=exclass),
tatsu.exceptions.FailedParse: (1:183) no available options :,
(@x2:gs-AffectingDirectedMotion( <mood>imperative ^ <gs-route>(x3:gs-GeneralizedRoute ^ <gs-destination>x4:gs-GeneralizedLocation) ^ <gum-actee>(x1:gum-SimpleThing ^ <relation>and ^ <item1>(w2:slm-Book ^ book ^ <det>the ^ <ident>specific ^ <quant>singular) ^ <item2>w5:slm-Cup) ^ <gum-processInConfiguration>(w0:slm-Putting ^ slm-Driving)) ^ @x6:gs-SpatialLocating( <gs-locatum>(w5:slm-Cup ^ cup ^ <det>the ^ <ident>specific ^ <quant>singular) ^ <gs-placement>(x5:gs-GeneralizedLocation ^ <gs-hasSpatialModality>(w6:gum-FunctionalControlledExternal ^ slm-On) ^ <gs-relatum>(w8:slm-Table ^ slm-Table ^ <det>the ^ <ident>specific ^ <quant>singular)))),
                                                                                                                                                                                      ^,
role,
variable,
role,
nominal,
term,
semspec,
start,
[pid: 8|app: 0|req: 1/1] 172.24.0.5 () {50 vars in 983 bytes} [Fri Nov  9 19:17:51 2018] POST /openccg/parse => generated 291 bytes in 2987 msecs (HTTP/1.0 500) 2 headers in 84 bytes (1 switches on core 0),
```

While this is bad enough, the server should at least throw a proper warning back to the user. Both issues need to be addressed!

**Comment by shoeffner** [comment]
The reason the parse does not work is that `<item1>` (and `<item2>`) contain numeric characters.
